name: codespace-off

on:
  workflow_dispatch: {}
  schedule: [cron: '0 21 * * *'] # UTC time (1am in Baku UTC+04:00)
  push:
    branches: [master, main]
    paths: [.github/workflows/codespace-off.yml]

concurrency:
  group: ${{ github.ref }}-codespace
  cancel-in-progress: true

jobs:
  switch-off:
    runs-on: ubuntu-latest
    steps:
    - name: Power off the codespace server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.hetzner.cloud/v1/servers/${{ secrets.HCLOUD_CODESPACE_SERVER_ID }}/actions/poweroff'
        method: 'POST'
        customHeaders: '{"Authorization": "Bearer ${{ secrets.HCLOUD_API_KEY }}"}'
