name: update

on:
  workflow_dispatch:
  schedule: [cron: '0 0 */1 * *']
  push:
    branches: [master, main]

jobs:
  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: templates/README.md
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name != 'pull_request'
        with:
          commit_message: 'Update generated README'
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
